const TOP_LEFT_X = 693;
const TOP_LEFT_Y = 46;

module.exports = {
  TOP_LEFT_X,
  TOP_LEFT_Y,
  WIDTH: 532,
  HEIGHT: 946,
  FIRST_MENU_BUTTON: { x: TOP_LEFT_X + 37, y: TOP_LEFT_Y + 929 },
  SECOND_MENU_BUTTON: { x: TOP_LEFT_X + 130, y: TOP_LEFT_Y + 929 },
  FOURTH_MENU_BUTTON: { x: TOP_LEFT_X + 312, y: TOP_LEFT_Y + 929 }
};
